{
  config,
  lib,
  ...
}: let
  cfg = config.local.security.fingerprint;
in {
  options.local.security.fingerprint = {
    enable = lib.mkEnableOption "fingerprint authentication through fprintd";

    pamServices = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [
        "login"
        "sudo"
        "polkit-1"
        "greetd"
      ];
      description = "PAM services that may authenticate with an enrolled fingerprint.";
    };

    tod = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "Use the Touch OEM Driver (TOD) stack for the fingerprint reader.";
      };

      driver = lib.mkOption {
        type = lib.types.nullOr lib.types.package;
        default = null;
        description = "Machine-specific TOD fingerprint driver package.";
      };
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = !cfg.tod.enable || cfg.tod.driver != null;
        message = "local.security.fingerprint.tod.driver must be set when TOD is enabled.";
      }
    ];

    services.fprintd = {
      enable = true;
      tod = {
        enable = cfg.tod.enable && cfg.tod.driver != null;
        driver = lib.mkIf (cfg.tod.enable && cfg.tod.driver != null) cfg.tod.driver;
      };
    };

    environment.systemPackages = lib.mkIf (cfg.tod.enable && cfg.tod.driver != null) [cfg.tod.driver];
    services.udev.packages = lib.mkIf (cfg.tod.enable && cfg.tod.driver != null) [cfg.tod.driver];

    # fprintd's default PAM integration covers services generated by NixOS.
    # Keep this explicit for the display manager and polkit services used by
    # this configuration, and for any service selected through pamServices.
    security.pam.services = lib.genAttrs cfg.pamServices (_: {
      fprintAuth = true;
    });
  };
}
