[[profile]]
name = "builtin-only"

[[profile.output]]
search = "n=eDP-1"
enable = true
mode = "preferred"
position = "0,0"
scale = 1.25

[[profile]]
name = "external-only"

[[profile.output]]
search = "n=eDP-1"
enable = false

[[profile.output]]
search = "s=WT6A83TAU0001"
enable = true
mode = "best"
position = "0,0"
scale = 1.5
